# Generated by Django 2.1.7 on 2019-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190317_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneverified',
            field=models.BooleanField(default=False),
        ),
    ]
