# Generated by Django 2.1.7 on 2019-03-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190330_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendanceupdated',
            field=models.BooleanField(default=False),
        ),
    ]
